name: CI
on:
push:
    branches: [ develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
#   push:
#     branches: [ develop ]
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with: 
#           node-version: "16.x"
#       - name: Install dependencies
#         run: npm install
#       - name: Run Build
#         run: npm install
#   prod:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12 
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "cube-web-app"
#           heroku_email: "noe.louvel@viacesi.fr"
